### ISSUE TITLE
Allow multiple gov tokens per projectId

### ISSUE THREAD

**Issue by mktcode** [OpenQDev/OpenQ-Contracts#23]
https://github.com/Octobay/contracts/blob/9eb6c25fb9b8b389f9cd6c1bc57f8d33096df88c/contracts/OctobayGovernor.sol#L86

The identifier of a governance department must be the token address, since there can be more than one governance token for the same GitHub repo/org.

**Comment by JasperTimm** [comment]
@mktcode - looking at this now, how should this affect the GovNFTs? Do we also want the ability to have a GovNFT per gov token or is that per project?

**Comment by mktcode** [comment]
First intuitive thought: Per gov token. Maybe something like an organization-wide super powerful master key NFT, the one ring to rule them all, might be something interesting for the future. But I'd say let's keep it simple for now. NFTs always belong to a certain gov token.
