### ISSUE TITLE
confirmCreateGovernanceToken seems to consume more gas than the default limit for a CL node

### ISSUE THREAD

**Issue by mktcode** [OpenQDev/OpenQ-Contracts#25]
https://github.com/Octobay/contracts/blob/dc3d41cd702eed9ceeb914602218929c4a012d49/contracts/Octobay.sol#L324-L343

In my local node I set this env var: `ETH_GAS_LIMIT_DEFAULT=5000000`
which is probably a far to big number.
The default value in the CL config is: `ETH_GAS_LIMIT_DEFAULT=500000` (a `0` less)

Also in the current chainlink docs, this var doesn't even appear any more: https://docs.chain.link/docs/configuration-variables

Thre's now:
https://docs.chain.link/docs/configuration-variables#eth_gas_bump_threshold
https://docs.chain.link/docs/configuration-variables#eth_gas_bump_wei
https://docs.chain.link/docs/configuration-variables#eth_gas_bump_percent
https://docs.chain.link/docs/configuration-variables#eth_gas_price_default

In any case, if possible, we should optimize this function.

Here's an example transaction: https://kovan.etherscan.io/tx/0x78b86ca291e47ac01ba52f49a2d8f3836cd17bae4fbe32b8b8eb614cc820a00a
It consumes ~3x the normal default value (500k).

**Comment by JasperTimm** [comment]
I can take a look in detail at the gas costs for this, but I'm going to assume that the biggest part is the cost of the contract deployment for the new token.

The first solution that comes to mind is to create the token before the confirmation and only add the token to the relevant mappings on confirmation.

**Comment by JasperTimm** [comment]
Hmmm, I can't assign the issue to myself. But feel free to assign it to me.

**Comment by mktcode** [comment]
I assigned it to you now and also changed the permissions.

>  I'm going to assume that the biggest part is the cost of the contract deployment for the new token.

Absolutely. Creating the token before confirmation seems to be a bit "risky" though. I'd be interested in how much of a problem it still is after a general professional gas optimization. If gas efficiency is a topic that triggers your dev curiosity anyway... have fun with it. :D

**Comment by JasperTimm** [comment]
Gas efficiency is definitely something I will spend more time looking at in the near future.

What "risks" do you see with doing the deployment beforehand though? It's not really that different from someone else going and deploying their own copy of the gov token code right? What really matters is whether we recognise it as a valid token in our mappings.

**Comment by mktcode** [comment]
> What "risks" do you see with doing the deployment beforehand though?

Nothing actually. With "beforehand" I guess you mean in the function triggering the oracle request. If that request fails, we have just added some waste to the blockchain. We said we gonna implement failure responses though, so we could delete it again.

Anyway... I think that approach is indeed totally valid. And in the frontend we can actually control the gas limit for the transaction if needed.

**Comment by JasperTimm** [comment]
Cool I'll do this then.

When you mentioned "delete it" I started to scratch my head, then I remembered that there's a `selfdestruct`, but apparently the code still stays on chain and to those executing it they might not notice a difference. So it's probably fine for us to leave it I think.
