### ISSUE TITLE
Use node_id to store github user info

### ISSUE THREAD

**Issue by 0xSachinK** [OpenQDev/OpenQ-Contracts#3]
Github usernames can change. Hence we need to store `node_id` of github users, which remains constant for a given user.

**Comment by mktcode** [comment]
Users are now stored in a separate contract, where the node IDs are being used now.

https://github.com/Octobay/contracts/blob/main/contracts/UserAddressStorage.sol

Needs updates in app as well. https://github.com/Octobay/app/issues/67
